# Generated by Django 6.0 on 2026-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], max_length=20)),
                ('race_date', models.DateTimeField(auto_now_add=True)),
                ('total_rolls', models.IntegerField(blank=True, null=True)),
                ('second_place', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], max_length=20, null=True)),
                ('last_place', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-race_date'],
            },
        ),
    ]
